### ISSUE TITLE
Sound does not work with longer songs

### ISSUE THREAD

**Issue by ClaireSoftware** [szymor/yatka#2]
Hello! I compiled this program myself, and I tried swapping out the songs for some longer ones (same sample rate as originals, of course), but it seems to crash/have seemingly random loud sounds after the first song. I'd love to help fix this issue, but I'm not too confident with SDL programming myself. Do you have any ideas as to what might be causing it?

**Comment by szymor** [comment]
First things first - what platform (OS, CPU, RAM) do you compile for?
I suspect that I do not handle properly song switching - one song should be explicitly stopped when selecting another one. It would be helpful if you provide crash dump with debug symbols enabled or at least the troublesome music file you mentioned.

**Comment by szymor** [comment]
As the issue cannot be reproduced and the submitter does not cooperate, I close the ticket.
