### ISSUE TITLE
We need a Discord for this!

### ISSUE THREAD

**Issue by Iqra77777** [szymor/yatka#6]

**Comment by szymor** [comment]
I will create a Discord server when more people start to engage in the project. At the current stage of development I get little feedback about the game.

**Comment by Iqra77777** [comment]
I see. It's ok though. I can wait. Also love the game. You should
definitely add t spin though.

**Comment by szymor** [comment]
T-spins are available, they came with SRS implementation in v0.7. However, they do not affect scoring system. If you encounter any issues, please report.

**Comment by Iqra77777** [comment]
I see. Well If you do have a discord id you can friend me. My id is
Iqra77777#4361. Also if there's a customizable option in the next update
like putting in your own skins that would be great. For reference I'm
tagging some pics of said skins

**Comment by szymor** [comment]
Unfortunately, I see no pictures if you have send me any. I am aware that the current way of handling skins is not designer-friendly if you use the OPK variant of the game. However, it is still possible. You just need to unpack the OPK (which is a squashfs archive) and copy your skin to the "skins" folder. I am sorry for any related inconvenience but skin designing was thought with developers in mind. Feel free to fork the game repository and develop skins on your own.

Speaking of Discord, I am available on some servers under nickname "vamastah". Do not hesitate to contact me :smile:

**Comment by Iqra77777** [comment]
Are you in the official Hard Drop discord by any chance? If you aren't you
should join it! It's the place where all tetris players hang out! Here's
the link: https://discord.gg/EHgm7E6GT6

**Comment by Auisce** [comment]
What do you think of the current skins?

**Comment by Iqra77777** [comment]
I like them. Also really liked the Pen'n'paper skin. Hey can you send me
like a generic blue letter font? I need one cause i'm making a skin

**Comment by Iqra77777** [comment]
Oh just realised you're a new person. Sorry about that. I am trying to make
a skin though.

**Comment by Iqra77777** [comment]
Love them! Also really like the pen'n'paper skin.

**Comment by Iqra77777** [comment]
Also I am using the Powkiddy v90 to play Yatka so I am not using the opk
file.

**Comment by Iqra77777** [comment]
So I found two pics that could be turned into a skin. If you could please
add this in the next update I would be grateful. I am linking you the pics
in links so that Github dosent make it not appear.
Here are the links: 1. https://tetrio.team2xh.net/images/skins/n30n/n30n.png
2.
https://img.pixers.pics/pho_wat(s3:700/FO/45/77/19/26/700_FO45771926_a704667a730bc2ad3a05ec7daaae8ef0.jpg,700,438,cms:2018/10/5bd1b6b8d04b8_220x50-watermark.png,over,480,388,jpg)/wall-murals-dark-blue-forest.jpg.jpg

**Comment by szymor** [comment]
@Auisce not sure if it was the question towards me, but the skins I liked got merged into the master branch, so I think this fact is self-explanatory. I like them a lot and I am waiting for more from you :smiley: 

@Iqra77777 
1) Speaking of Hard Drop Discord server, I never heard of it before, but I will surely visit it some day.
2) I have not used any font while creating the background of Pen'n'Paper skin. Every text you see there was hand-written. The font used to display score and other texts changing during the gameplay can be found in the skin folder.
3) If you use Powkiddy V90, then the case is simple - you just need to create a skin and copy it to the "skins" folder. Take a look there to see how other skins work. The skin description file is quite simple so you should cope with it.

**Comment by Iqra77777** [comment]
I'll try and make a skin later. So you need a new hold space for people to
know what their next hold piece is other than swapping the next piece. Also
you need updated sounds like hard drop/soft drop/lock/hold and finally a
tetris sound. I can only suggest stuff and I'm sorry if I'm adding work to
you, I just wanna see this game to its full potential. Also hope you have a
great day m8. And hope you make a full blue skin in the next update. Hope
to email you again.
Iqra77777

**Comment by Auisce** [comment]
@Iqra77777 
What do you mean a full blue skin?

@szymor 
Yeah I should go back and update the GamBoi skin to begin with and get the hang of 0.7 before implementing the next one.

**Comment by Iqra77777** [comment]
Like Blue tetromino's, blue background with scoring system. Like that

**Comment by szymor** [comment]
Most ideas from this thread have been implemented, so if there are no other things to talk about, I will close the ticket after 7 days of inactivity.
